/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebas.edvin_reyes;

import com.gt.correcion.Corrector;
import com.gt.modo_oscuro.Letrista;
import com.gt.modo_oscuro.Pintor;
import com.gt.modo_oscuro.PintorBT;
import com.gt.modo_oscuro.Tema1;
import com.gt.modo_oscuro.Tema2;
import com.gt.modo_oscuro.Tema3;
import com.pe.iinsPre.Insertar;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import javax.swing.JButton;
import javax.swing.JLabel;

import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.plaf.basic.BasicButtonUI;


import javax.swing.plaf.basic.BasicToggleButtonUI;

/**
 *
 * @author Usuario
 */
public class Biologia1 extends javax.swing.JFrame {
    
    int modonumber=1;
    JButton curso1 = new JButton("Matemática");
    JButton curso2 = new JButton("Biología");
    JButton curso3 = new JButton("Comunicación");
    Tema1 oscu= new Tema1();
    Tema2 cla=new Tema2();
    Tema3 pinky=new Tema3();
    String user;
    

    
    
    public Biologia1(String user, int modo) {
        initComponents();
        modonumber=modo;
        this.user=user;
        jLabel2.setText("Bienvenido "+user+" ,responde:");
        this.setLocationRelativeTo(null);
        switch (modo%3) {
            case 1:
                modoCla();
                break;
            case 2:
                modoOscu();
                break;
            case 0:
                modoPinky();
                break;
            default:
                break;
        }
        
        JButton [] btns={curso1, curso2, curso3}; 
        for (JButton btn: btns){
            btn.setForeground(Color.WHITE);
            btn.setFont(new java.awt.Font("Arial", 2, 16));
            
        }
        curso2.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                curso1MouseClicked(e);
                
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        String[][]rellenar={{"¿Qué es el ecosistema?","Sistema estático de animales",
                            "interacción de animales y plantas", "Sinónimo de nicho", "sistema dinámico de seres vivos su medio"},
                            {"Oparín propueso la teoría:","del Big Bang","Deriva continental", "Evolución", "Quimiosintética"},
                            {"Seleccione un elemento oligogénico","O","K", "Mg", "Fr"}};
        JPanel [] paneles={alternativasPanel,alternativasPanel1, alternativasPanel2};
        JLabel [] enun={enunciadoJLabel,enunciadoJLabel1,enunciadoJLabel2};
        for (int i = 0; i < 3; i++) {
            new Insertar(rellenar[i][0], 
                    rellenar[i][1], 
                    rellenar[i][2], 
                    rellenar[i][3], rellenar[i][4]).escribir(enun[i], paneles[i].getComponents());
        }
        
        
        
                
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        arribaPanel = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        centralPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        preguntasJPanel = new javax.swing.JPanel();
        pregunta1panel = new javax.swing.JPanel();
        enunciadoJLabel = new javax.swing.JLabel();
        alternativasPanel = new javax.swing.JPanel();
        claveA = new javax.swing.JRadioButton();
        claveA1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        infoJLabel = new javax.swing.JLabel();
        pregunta1panel1 = new javax.swing.JPanel();
        enunciadoJLabel1 = new javax.swing.JLabel();
        alternativasPanel1 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        infoJLabel1 = new javax.swing.JLabel();
        pregunta1panel2 = new javax.swing.JPanel();
        enunciadoJLabel2 = new javax.swing.JLabel();
        alternativasPanel2 = new javax.swing.JPanel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        infoJLabel2 = new javax.swing.JLabel();
        abajoPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 850));

        arribaPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        arribaPanel.setPreferredSize(new java.awt.Dimension(0, 100));
        arribaPanel.setLayout(new java.awt.BorderLayout());

        jToggleButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuosc.png"))); // NOI18N
        jToggleButton1.setToolTipText("");
        jToggleButton1.setPreferredSize(new java.awt.Dimension(50, 25));
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseEntered(evt);
            }
        });
        arribaPanel.add(jToggleButton1, java.awt.BorderLayout.LINE_START);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dia.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        arribaPanel.add(jButton4, java.awt.BorderLayout.LINE_END);

        jPanel2.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Biología");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        arribaPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(arribaPanel, java.awt.BorderLayout.PAGE_START);

        centralPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        centralPanel.setPreferredSize(new java.awt.Dimension(0, 100));
        centralPanel.setLayout(new java.awt.BorderLayout(0, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RESPONDA LAS SIGUIENTES PREGUNTAS");
        jLabel2.setToolTipText("");
        jLabel2.setPreferredSize(new java.awt.Dimension(34, 50));
        centralPanel.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        preguntasJPanel.setLayout(new java.awt.GridLayout(3, 0, 0, 20));

        pregunta1panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 140, 250), 1, true));
        pregunta1panel.setLayout(new java.awt.GridLayout(3, 0));

        enunciadoJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enunciadoJLabel.setForeground(new java.awt.Color(0, 0, 0));
        enunciadoJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enunciadoJLabel.setText("jLabel4");
        pregunta1panel.add(enunciadoJLabel);

        alternativasPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(claveA);
        claveA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        claveA.setForeground(new java.awt.Color(0, 0, 0));
        claveA.setText("jRadioButton1");
        alternativasPanel.add(claveA);

        buttonGroup1.add(claveA1);
        claveA1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        claveA1.setForeground(new java.awt.Color(0, 0, 0));
        claveA1.setText("jRadioButton2");
        alternativasPanel.add(claveA1);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton3.setText("jRadioButton3");
        alternativasPanel.add(jRadioButton3);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton4.setText("jRadioButton4");
        alternativasPanel.add(jRadioButton4);

        pregunta1panel.add(alternativasPanel);

        infoJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        infoJLabel.setForeground(new java.awt.Color(0, 0, 0));
        infoJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pregunta1panel.add(infoJLabel);

        preguntasJPanel.add(pregunta1panel);

        pregunta1panel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 140, 250), 1, true));
        pregunta1panel1.setLayout(new java.awt.GridLayout(3, 0));

        enunciadoJLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enunciadoJLabel1.setForeground(new java.awt.Color(0, 0, 0));
        enunciadoJLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enunciadoJLabel1.setText("jLabel4");
        pregunta1panel1.add(enunciadoJLabel1);

        alternativasPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton5.setText("jRadioButton1");
        alternativasPanel1.add(jRadioButton5);

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton6.setText("jRadioButton2");
        alternativasPanel1.add(jRadioButton6);

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton7.setText("jRadioButton3");
        alternativasPanel1.add(jRadioButton7);

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton8.setText("jRadioButton4");
        alternativasPanel1.add(jRadioButton8);

        pregunta1panel1.add(alternativasPanel1);

        infoJLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        infoJLabel1.setForeground(new java.awt.Color(0, 0, 0));
        infoJLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pregunta1panel1.add(infoJLabel1);

        preguntasJPanel.add(pregunta1panel1);

        pregunta1panel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 140, 250), 1, true));
        pregunta1panel2.setLayout(new java.awt.GridLayout(3, 0));

        enunciadoJLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enunciadoJLabel2.setForeground(new java.awt.Color(0, 0, 0));
        enunciadoJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        enunciadoJLabel2.setText("jLabel4");
        pregunta1panel2.add(enunciadoJLabel2);

        alternativasPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton9.setText("jRadioButton1");
        alternativasPanel2.add(jRadioButton9);

        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton10.setText("jRadioButton2");
        alternativasPanel2.add(jRadioButton10);

        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton11.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton11.setText("jRadioButton3");
        alternativasPanel2.add(jRadioButton11);

        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton12.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton12.setText("jRadioButton4");
        alternativasPanel2.add(jRadioButton12);

        pregunta1panel2.add(alternativasPanel2);

        infoJLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        infoJLabel2.setForeground(new java.awt.Color(0, 0, 0));
        infoJLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pregunta1panel2.add(infoJLabel2);

        preguntasJPanel.add(pregunta1panel2);

        centralPanel.add(preguntasJPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(centralPanel, java.awt.BorderLayout.CENTER);

        abajoPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 10, 10, 10));
        abajoPanel.setPreferredSize(new java.awt.Dimension(0, 100));
        abajoPanel.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrowbackcla.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        abajoPanel.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Corregir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        abajoPanel.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrowforwardcla.png"))); // NOI18N
        abajoPanel.add(jButton3);

        getContentPane().add(abajoPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//       new Corrector().corregir(jRadioButton1, infoJLabel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
//       new Corrector().corregir(claveA , infoJLabel);
//       new Corrector().corregir(claveB3, infoJLabel1);
//       new Corrector().corregir(claveC2, infoJLabel2);
       
        JRadioButton [] respuestas={jRadioButton4,jRadioButton8,jRadioButton11};
        JLabel [] alertas = {infoJLabel,infoJLabel1,infoJLabel2};
        
        for (int i = 0; i < 3; i++) {
            new Corrector().corregir(respuestas[i], alertas[i]);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jToggleButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseEntered
        // TODO add your handling code here:
        //Se peude mejorar con un slide y con el método is showing para q se recontruya
        
    }//GEN-LAST:event_jToggleButton1MouseEntered

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:
        if (jToggleButton1.isSelected()){
            jPanel2.remove(jLabel1);
            JButton [] btns ={curso1, curso2, curso3};
            for (JButton btn : btns) {
                jPanel2.add(btn);
                
                
            }
            new PintorBT(oscu.getBotones1(),oscu.getBotones1c()).pintar(jPanel2);
            jPanel2.setLayout(new java.awt.GridLayout(1,3,10,10));
            this.setSize(this.getWidth()+1, this.getHeight());
            this.setSize(this.getWidth()-1, this.getHeight());
            jButton4.setEnabled(false);
            
        }else{
            jPanel2.removeAll();
            jPanel2.setLayout(new java.awt.BorderLayout());
            jPanel2.add(jLabel1);
            this.setSize(this.getWidth()+1, this.getHeight());
            this.setSize(this.getWidth()-1, this.getHeight());
            jButton4.setEnabled(true);
        }

    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        new inicio(modonumber).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        modonumber++;
        switch (modonumber%3) {
            case 1:
                modoCla();
                break;
            case 2:
                modoOscu();
                break;
            case 0:
                modoPinky();
                break;
            default:
                break;
        }
            
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void curso1MouseClicked(java.awt.event.MouseEvent evt) {
        
//        new Biologia1(user,jToggleButton2.isSelected()).setVisible(true);
        this.dispose();
    } 
    private void modoOscu(){
        new Pintor(oscu.getFondo2()).pintar(arribaPanel);
        new Pintor(oscu.getFondo1()).pintar(centralPanel);
        new Pintor(oscu.getFondo1()).pintar(abajoPanel);
        new PintorBT(oscu.getBotones1(),cla.getBotones1c()).pintar(abajoPanel);
        jToggleButton1.setBackground(oscu.getFondo2());
        jToggleButton1.setUI(new BasicToggleButtonUI());
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuscla.png")));
        jButton4.setBackground(oscu.getFondo2());
        jButton4.setUI(new BasicButtonUI());
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dia.png")));
        new Letrista(Color.WHITE).pintar(arribaPanel);
        new Letrista(Color.WHITE).pintar(centralPanel);
    }
    private void modoCla(){
        new Pintor(cla.getFondo1()).pintar(arribaPanel);
        new Pintor(cla.getFondo1()).pintar(centralPanel);
        new Pintor(cla.getFondo1()).pintar(abajoPanel);
        new PintorBT(cla.getBotones1(),cla.getBotones1c()).pintar(abajoPanel);
        jToggleButton1.setBackground(cla.getFondo1());
        jToggleButton1.setUI(new BasicToggleButtonUI());
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuosc.png")));
        jButton4.setBackground(cla.getFondo1());
        jButton4.setUI(new BasicButtonUI());
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/noche.png")));
        new Letrista(Color.BLACK).pintar(arribaPanel);
        new Letrista(Color.BLACK).pintar(centralPanel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biologia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biologia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biologia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biologia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biologia1(null, 1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abajoPanel;
    private javax.swing.JPanel alternativasPanel;
    private javax.swing.JPanel alternativasPanel1;
    private javax.swing.JPanel alternativasPanel2;
    private javax.swing.JPanel arribaPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPanel centralPanel;
    private javax.swing.JRadioButton claveA;
    private javax.swing.JRadioButton claveA1;
    private javax.swing.JLabel enunciadoJLabel;
    private javax.swing.JLabel enunciadoJLabel1;
    private javax.swing.JLabel enunciadoJLabel2;
    private javax.swing.JLabel infoJLabel;
    private javax.swing.JLabel infoJLabel1;
    private javax.swing.JLabel infoJLabel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel pregunta1panel;
    private javax.swing.JPanel pregunta1panel1;
    private javax.swing.JPanel pregunta1panel2;
    private javax.swing.JPanel preguntasJPanel;
    // End of variables declaration//GEN-END:variables

    private void modoPinky() {
        new Pintor(pinky.getFondo1()).pintar(arribaPanel);
        new Pintor(pinky.getFondo2()).pintar(centralPanel);
        new Pintor(pinky.getFondo2()).pintar(abajoPanel);
        new PintorBT(pinky.getBotones1(),pinky.getBotones1c()).pintar(abajoPanel);
        jToggleButton1.setBackground(pinky.getFondo1());
        jToggleButton1.setUI(new BasicToggleButtonUI());
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menuscla.png")));
        jButton4.setBackground(pinky.getFondo1());
        jButton4.setUI(new BasicButtonUI());
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/custom.png")));
        new Letrista(Color.WHITE).pintar(arribaPanel);
        new Letrista(Color.WHITE).pintar(centralPanel);
    }
}
